name: ai-s3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy=2.3
  - pandas=2.3
  - matplotlib=3.10
  - seaborn=0.13
  - scikit-learn=1.7
  - scipy=1.16
  - jupyterlab=4.4
  - ipywidgets=8.1
  - plotly=6.2
  - pip=25.2
  - openpyxl=3.1
  - requests=2.32
  - graphviz=13.1
  - python-graphviz=0.16
  - pip:
      - streamlit==1.48
